package com.xgen.mongot.index.lucene;

import static com.xgen.mongot.util.Check.checkState;

import com.xgen.mongot.cursor.batch.BatchCursorOptions;
import com.xgen.mongot.index.BatchProducer;
import com.xgen.mongot.index.IntermediateMetricBucket;
import com.xgen.mongot.index.query.collectors.MetricsCollector;
import com.xgen.mongot.util.Bytes;
import com.xgen.mongot.util.bson.BsonArrayBuilder;
import java.io.IOException;
import java.util.ArrayDeque;
import java.util.Map;
import java.util.Queue;
import java.util.TreeMap;
import org.bson.BsonArray;

/**
 * Outputs batches of intermediate meta results for a metrics collector query against a sharded
 * collection (or one index partition). It always outputs a "count" document first, followed by the
 * {@link IntermediateMetricBucket}s of every metric, which will later be merged using the plan
 * generated by {@link com.xgen.mongot.server.command.search.ShardedSearchPlanner} or by {@link
 * MetricsMergingBatchProducer}.
 */
class LuceneMetricsCollectorMetaBatchProducer implements BatchProducer {

  private final long totalHits;
  private final MetricsCollector metricsCollector;
  /** Keyed by metric name. */
  private final Map<String, NumericMetricAccumulator> accumulatorsByMetricName;

  private final Queue<IntermediateMetricBucket> pendingBuckets;
  private boolean countProduced;
  private boolean closed;

  LuceneMetricsCollectorMetaBatchProducer(
      long totalHits,
      MetricsCollector metricsCollector,
      Map<String, NumericMetricAccumulator> accumulatorsByMetricName) {
    this.totalHits = totalHits;
    this.metricsCollector = metricsCollector;
    this.accumulatorsByMetricName = accumulatorsByMetricName;
    this.pendingBuckets = decomposeAll(accumulatorsByMetricName);
    this.countProduced = false;
    this.closed = false;
  }

  /** Decomposes every metric into intermediate buckets, in metric name order for determinism. */
  private static Queue<IntermediateMetricBucket> decomposeAll(
      Map<String, NumericMetricAccumulator> accumulatorsByMetricName) {
    Queue<IntermediateMetricBucket> buckets = new ArrayDeque<>();
    new TreeMap<>(accumulatorsByMetricName)
        .forEach((name, accumulator) -> buckets.addAll(accumulator.decompose(name)));
    return buckets;
  }

  long getTotalHits() {
    return this.totalHits;
  }

  MetricsCollector getMetricsCollector() {
    return this.metricsCollector;
  }

  Map<String, NumericMetricAccumulator> getAccumulatorsByMetricName() {
    return this.accumulatorsByMetricName;
  }

  @Override
  public void execute(Bytes sizeLimit, BatchCursorOptions queryCursorOptions) throws IOException {}

  @Override
  public BsonArray getNextBatch(Bytes resultsSizeLimit) throws IOException {
    checkState(!this.closed, "Cannot call getNextBatch() on closed BatchProducer.");
    BsonArrayBuilder resultsBuilder = BsonArrayBuilder.withLimit(resultsSizeLimit);

    if (!this.countProduced) {
      if (!resultsBuilder.append(
          LuceneFacetCollectorMetaBatchProducer.getCountRawBsonDoc(this.totalHits))) {
        throw new IllegalStateException("Could not fit count bucket in meta buckets batch.");
      }
      this.countProduced = true;
    }

    while (!this.pendingBuckets.isEmpty()
        && resultsBuilder.append(this.pendingBuckets.peek().toRawBson())) {
      this.pendingBuckets.remove();
    }
    return resultsBuilder.build();
  }

  @Override
  public boolean isExhausted() {
    return this.countProduced && this.pendingBuckets.isEmpty();
  }

  @Override
  public void close() {
    this.closed = true;
    this.pendingBuckets.clear();
  }
}
