package com.xgen.mongot.index;

import com.xgen.mongot.util.bson.parser.BsonDocumentBuilder;
import com.xgen.mongot.util.bson.parser.DocumentEncodable;
import com.xgen.mongot.util.bson.parser.Field;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import org.bson.BsonDocument;

/**
 * IntermediateMetricBucket represents one component of a metric produced for a metrics collector
 * query run against a sharded collection. A metric is decomposed into algebraic components ({@link
 * Component}) so that partial results can be merged exactly: the merged {@code sum} and {@code
 * count} are their totals, and the merged {@code min}/{@code max} are the extremes. These buckets
 * are later merged using the plan generated by {@link
 * com.xgen.mongot.server.command.search.ShardedSearchPlanner}.
 *
 * <pre>
 *   {type: "metric", tag: "&lt;metric name&gt;", bucket: "sum",   value: 12.5}
 *   {type: "metric", tag: "&lt;metric name&gt;", bucket: "count", count: 3}
 * </pre>
 *
 * @param tag The name of the metric.
 * @param component The metric component this bucket carries.
 * @param value The payload of the {@code sum}, {@code min} and {@code max} components.
 * @param count The payload of the {@code count} component.
 */
public record IntermediateMetricBucket(
    String tag, Component component, Optional<Double> value, Optional<Long> count)
    implements DocumentEncodable {

  private static class Fields {
    static final Field.Required<Type> TYPE =
        Field.builder("type").enumField(Type.class).asCamelCase().required();

    static final Field.Required<String> TAG = Field.builder("tag").stringField().required();

    static final Field.Required<String> BUCKET = Field.builder("bucket").stringField().required();

    static final Field.Optional<Double> VALUE =
        Field.builder("value").doubleField().optional().noDefault();

    static final Field.Optional<Long> COUNT =
        Field.builder("count").longField().optional().noDefault();
  }

  public enum Type {
    METRIC
  }

  public enum Component {
    SUM("sum"),
    COUNT("count"),
    MIN("min"),
    MAX("max");

    private final String name;

    Component(String name) {
      this.name = name;
    }

    /** Returns the name of this component as it appears in the {@code bucket} field. */
    public String getName() {
      return this.name;
    }
  }

  /**
   * Decomposes one metric's accumulated state into intermediate buckets. {@code sum} and {@code
   * count} are always emitted; {@code min} and {@code max} only when at least one value was seen,
   * so that empty partials do not distort the merged extremes.
   */
  public static List<IntermediateMetricBucket> decompose(
      String tag, double sum, long count, double min, double max) {
    List<IntermediateMetricBucket> buckets = new ArrayList<>(4);
    buckets.add(ofValue(tag, Component.SUM, sum));
    buckets.add(
        new IntermediateMetricBucket(tag, Component.COUNT, Optional.empty(), Optional.of(count)));
    if (count > 0) {
      buckets.add(ofValue(tag, Component.MIN, min));
      buckets.add(ofValue(tag, Component.MAX, max));
    }
    return buckets;
  }

  private static IntermediateMetricBucket ofValue(String tag, Component component, double value) {
    return new IntermediateMetricBucket(tag, component, Optional.of(value), Optional.empty());
  }

  @Override
  public BsonDocument toBson() {
    return BsonDocumentBuilder.builder()
        .field(Fields.TYPE, Type.METRIC)
        .field(Fields.TAG, this.tag)
        .field(Fields.BUCKET, this.component.getName())
        .field(Fields.VALUE, this.value)
        .field(Fields.COUNT, this.count)
        .build();
  }
}
